---
- name: Get Network Interfaces and MAC Addresses
  hosts: all
  remote_user: core
  gather_facts: yes
  tasks:
    - name: Display interfaces and MAC addresses
      debug:
        msg: "Interface {{ item }} has MAC address {{ ansible_facts[item]['macaddress']|default('N/A') }}"
      loop: "{{ ansible_interfaces }}"
